### PR TITLE
Add ProtonVPN

### PR DESCRIPTION
**Pull request by brianjking**
* Add ProtonVPN logo
* Add ProtonVPN links to VPN section

### CODE REVIEW

**Comment by brianjking** [comment]
@brianlovin -- I submitted the logo that ProtonVPN states to use as per their [ProtonVPN/ProtmailMail Press Guide](https://protonvpn.com/press).

I compressed the `protonvpn.png` file through tinypng.com as per your request though and added it to the PR.

**Comment by brianlovin** [comment]
> I submitted the logo that ProtonVPN states to use as per their ProtonVPN/ProtmailMail Press Guide.

Since we're putting this in the "Apps" section though, it might make sense to just use the app icon? I don't mind either way since they're close enough, but if we don't use the app store icon can we add a white background to the image in this PR?

**Comment by brianjking** [comment]
Okay @brianlovin -- I added a jpeg which has been optimized and has a white background taken from [https://protonvpn.com/press](https://protonvpn.com/press). It's included in [this commit](https://github.com/brianlovin/security-checklist/pull/23/commits/265f71ea02ead76cd802a8842e9fde5a19a9557e).

**Comment by brianlovin** [comment]
Thank you @brianjking! And no worries on the app store image (I do the rounding in css anyways, so square images work)

**Comment by brianjking** [comment]
Ok, that's what I figured (re: rounding). I didn't take a look to confirm. All good to merge then?

**Comment by brianlovin** [comment]
oh @brianjking sorry last thing, could you delete the extra image in the `static/img` folder?

**Comment by brianjking** [comment]
Done.

**Pull request merged**
