### PR TITLE
feat: add startpage.com search engine

### PR DESCRIPTION
**Pull request by mstalfoort**

### CODE REVIEW

**Comment by brianlovin** [comment]
Startpage doesn't feel like the best candidate for this section, not because I don't think it's useful but because there is little transparency into the team and operation behind the product. I can see that it's made in Europe, but don't know anything about the team or data use.

**Comment by brianlovin** [comment]
Going to close for now, but happy to keep discussing here :)

**Comment by mstalfoort** [comment]
let me check if i can arrange the info you're looking after

**Comment by mstalfoort** [comment]
was https://github.com/brianlovin/security-checklist/issues/34 clear enough to re-open this pr or do you need more clarity?

**Pull request closed without merging**
