### PR TITLE
Add Mailfence

### PR DESCRIPTION
**Pull request by resto1231**
Hello,

I am quite new to Github, i finally found how to add the image asset but now how do i add it to the actual code itself? Thanks a lot if you take the time to reply

### CODE REVIEW

**Comment by brianlovin** [comment]
@resto1231 that asset needs to be added to the repo itself, thanks!

**Comment by resto1231** [comment]
Hello,

So i added the image asset on my branch since i cannot upload the asset directly to the master branch. Is this the way to do it? Thankss

**Comment by brianlovin** [comment]
Yep, on the branch is the right place! But now I'm seeing 2 images uploaded, instead of one :)

**Comment by resto1231** [comment]
I deleted the second picture it should be ok now, thanks!!

**Pull request merged**
