### PR TITLE
Added postale.io in email providers

### PR DESCRIPTION
**Pull request by DoobleD**
- Security [features](https://postale.io/features) (SSL/TLS encryption, PGP encryption, ClamAV antivirus, Rspamd antispam, ...).
- [Privacy policy](https://postale.io/privacy-policy) (the service collects username and email for registration/contact purposes, uses Stripe for payment, doesn't sell data, and respects RGDP).

### CODE REVIEW

**Comment by DoobleD** [comment]
Not sure if new pull requests notify potential reviewers automatically? @brianlovin?

**Comment by DoobleD** [comment]
Hey @brianlovin, thanks for looking at it! Any chance I can get some feedback on why this pull request was rejected?

**Comment by brianlovin** [comment]
This site is generally trying to target less tech savvy folks, aka "regular" internet users. This isn't always possible, as a lot of security tools require some technical literacy (VPNs, for example, require someone to learn about what it does). In this case, I felt that Postale did not look approachable or trustworthy compared to many of the other options. This feels closer to a service that an early adopter hacker might be interested in, but not someone who is looking for a reliable email provider.

**Comment by DoobleD** [comment]
Thanks for that explanation @brianlovin. Perhaps the service [reviews](https://www.trustpilot.com/review/postale.io?languages=all) could make you change your mind about it, but if not that's ok too! :)

**Pull request closed without merging**
