### PR TITLE
[Design] Add progress indicator on header

### PR DESCRIPTION
**Pull request by joachimesque**
#12

I've only started learning React a couple of weeks ago, so my code might not be the best it could be… but it works

image

### CODE REVIEW

**Comment by brianlovin** [comment]
@joachimesque I think the code is pretty solid overall, haven't taken too deep of a dive. But from a design perspective, what if we did this:

- make the progress bar full-width along the bottom of the header
- on hover, we show a tooltip or something that says 'n/y complete' or '20% complete' or something like that.

**Comment by joachimesque** [comment]
Here's a commit with the design tweaks you asked. I'm not yet sure if my code is accessible, so it's still a work in progress.

image

image

**Comment by joachimesque** [comment]
- the progress container is higher than the progress bar, for better click / touch affordance
- the header is now always white (the progress bar would have been making too big of a limit

I'm thinking of adding confetti (like these: https://codepen.io/ykadosh/pen/aaoZRB) when you reach the end of the progress bar. It's a fun & delightful thing to add, but I'm worried about performance. What's your opinion?

**Comment by brianlovin** [comment]
> I'm thinking of adding confetti (like these: https://codepen.io/ykadosh/pen/aaoZRB) when you reach the end of the progress bar. It's a fun & delightful thing to add, but I'm worried about performance. What's your opinion?

This would be fun! I'm not too worried about perf in this case.

Overall this PR is looking really nice so far! I think a couple last tweaks:

- can we make the progress bar 4px tall instead of 8px?
- let's remove the border radius on the progress bar
- can the progress bar be white until the *first* item is checked? otherwise it just sort of looks out of place to have the gray bar there for people who are just reading, and won't ever end up checking something off

**Comment by brianlovin** [comment]
The confetti was awesome! Let's change a couple small things:

- if 0 items have been checked, let's remove the hover tab on the navbar that shows '0 of 18 completed' since it's quite confusing what's being hovered
- when the confetti is triggered, can we change '18 of 18 completed' to something more like 'Checklist Complete!' ?

**Comment by brianlovin** [comment]
@joachimesque looks like one lingering flow error from the confetti component

**Comment by joachimesque** [comment]
I ran into a test Error that looked strange:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ components/Header/Confetti.js:111:12

Cannot create svg element because a callable signature is missing in object type [1] but exists in function type [2] in
property ref.
…

     /private/tmp/flow/flowlib_1880ea6c/react.js
 [2] 195│   | ((React$ElementRef<ElementType> | null) => mixed)
        :
 [1] 322│   declare export function useRef<T>(initialValue: ?T): {current: T | null};

…
```

This looks like a problem in Flow or in React. Switching the `svg` to a `div` makes the test pass.

**Comment by brianlovin** [comment]
Hm, super weird. I'm personally fine if you do a `$FlowIssue` on the line above to suppress this.

**Comment by brianlovin** [comment]
Well, all tests pass now...how about that @joachimesque :P

**Comment by joachimesque** [comment]
Yes, I encapsulated the `svg` in a `div`:

```
    <div ref={currentSquiggleConfetti} style={style}>
      <svg
        xmlns="http://www.w3.org/2000/svg" 
        viewBox="0 0 512 512">
        <path fill={style.fill} d="M428.127,0l-12.716,10.062l12.718-10.06c8.785,11.101,19.716,24.917,19.716,51.051 s-10.932,39.951-19.716,51.053c-7.382,9.331-12.716,16.072-12.716,30.927c0,14.854,5.334,21.594,12.716,30.925   c8.784,11.101,19.716,24.917,19.716,51.05c0,26.135-10.931,39.949-19.715,51.051c-7.383,9.331-12.717,16.072-12.717,30.927   c0,14.855,5.332,21.593,12.711,30.919l-25.435,20.124c-8.781-11.097-19.708-24.909-19.708-51.042 c0-26.135,10.931-39.949,19.715-51.051c7.383-9.331,12.717-16.072,12.717-30.927c0-14.855-5.335-21.595-12.717-30.926 c-8.784-11.101-19.715-24.916-19.715-51.049s10.931-39.95,19.715-51.051c7.383-9.331,12.717-16.072,12.717-30.928 c0-14.855-5.335-21.596-12.718-30.927L428.127,0z"/>
      </svg>
    </div>
```

Because I'm not too familiar with Flow yet ;)

**Comment by brianlovin** [comment]
If it works, it works! I'll merge master and ship this - amazing stuff @joachimesque this feels super nice :)

**Pull request merged**
