### PR TITLE
Using one password manager for both password management and 2FA is not good advice

### PR DESCRIPTION
**Pull request by felixfoertsch**
Hey guys,

I think using one password manager for both password management and 2FA is not good advice. You are creating a single point of failure. Of course it is better than nothing, but a project like this should at least have a disclaimer about this.

I added the disclaimer and reordered the list to reflect the advice.

Felix

### CODE REVIEW

**Comment by brianlovin** [comment]
Looks like this duplicated #38 right? Closing for now, we can re-open if I'm mistaken :)

**Comment by felixfoertsch** [comment]
@brianlovin this is a different topic. Sorry for not making sure everything passes before pushing. 🤓

**Comment by felixfoertsch** [comment]
Oh, my bad. It seems that I messed up my branches.

**Comment by brianlovin** [comment]
All good! Glad we got the changes in regardless :)

**Pull request closed without merging**
